//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareMemories.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareMemories.Application.Resources.ApplicationText", typeof(ApplicationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hello {0}&lt;/p&gt;
        ///&lt;p&gt;Thank you for registering.&lt;/p&gt;
        ///&lt;p&gt;Please confirm your email address by clicking the link below:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&apos;{1}&apos;&gt;Confirm Registration Email&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If you did not register for this site, please ignore this email.&lt;/p&gt;
        ///&lt;p&gt;Thanking you,&lt;br/&gt;O&apos;Neill Says!&lt;/p&gt;.
        /// </summary>
        internal static string ConfirmEmailTemplate {
            get {
                return ResourceManager.GetString("ConfirmEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hello {0}&lt;/p&gt;
        ///
        ///&lt;p&gt;Your 2FA by email has now been disabled.&lt;/p&gt;
        ///
        ///&lt;p&gt;If you have any questions contact our administration team at the email address below.&lt;/p&gt;
        ///
        ///&lt;p&gt;Administration Email: Support@MyDomain.Com&lt;/p&gt;
        ///
        ///&lt;p&gt;Thanking you,&lt;br/&gt;O&apos;Neill Says!&lt;/p&gt;.
        /// </summary>
        internal static string DisableTwoFactorAuthenticationTemplate {
            get {
                return ResourceManager.GetString("DisableTwoFactorAuthenticationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hello {0}&lt;/p&gt;
        ///
        ///&lt;p&gt;You are now enabled for 2FA by email, this is to re-enforce our security policy and for your protection online.&lt;/p&gt;
        ///
        ///&lt;p&gt;If you have any questions contact our administration team at the email address below.&lt;/p&gt;
        ///
        ///&lt;p&gt;Administration Email: Support@MyDomain.Com&lt;/p&gt;
        ///
        ///&lt;p&gt;Thanking you,&lt;br/&gt;O&apos;Neill Says!&lt;/p&gt;.
        /// </summary>
        internal static string EnableTwoFactorAuthenticationTemplate {
            get {
                return ResourceManager.GetString("EnableTwoFactorAuthenticationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}
        ///
        ///We received a request to reset your password. 
        ///
        ///Click on the Swagger API link &quot;/passwordGroup/VerifyPasswordResetAsync&quot; and enter your new password and the reset password token below:
        ///
        ///NB: Normally you will have a link here to bring you to the verification page to enter the new Password &amp; Token.
        /// 
        /// Reset password token: {1}
        ///
        /// If you did not request a password reset, please ignore this email.
        ///
        /// Thanking you
        /// O&apos;Neill Says!.
        /// </summary>
        internal static string ResetPasswordTemplate {
            get {
                return ResourceManager.GetString("ResetPasswordTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hello {0}&lt;/p&gt; 
        ///
        ///&lt;p&gt;You have received this 2FA email, as somebody is trying to log into your account.&lt;/p&gt; 
        ///
        ///&lt;p&gt;Please confirm that this is you, by clicking the Swagger API link &quot;/2FAGroup/Verify2FactorAuthenticationAsync&quot; and enter your Username and the 2FA Code below:&lt;/p&gt;
        ///
        ///&lt;p&gt;NB: Normally once you have attempted to login, a new page will be displayed to enter the 2FA code - which is from the same domain (a link from an email will not pass CORS security) - this is why you see the likes of eBay etc.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoFactorAuthenticationTemplate {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hello {0}&lt;/p&gt;
        ///&lt;p&gt;We received a request to unlock your account.&lt;/p&gt;
        ///&lt;p&gt;Unlock your account by clicking the link below:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&apos;{1}&apos;&gt;Unlock My Account&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If you did not make a request to unlock your account, please ignore this email and contact Administration - Support@MyDomain.Com&lt;/p&gt;
        ///&lt;p&gt;Thanking you,&lt;br/&gt;O&apos;Neill Says!&lt;/p&gt;.
        /// </summary>
        internal static string UnlockAccountTemplate {
            get {
                return ResourceManager.GetString("UnlockAccountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hello {0}&lt;/p&gt;
        ///&lt;p&gt;Your details have been updated.&lt;/p&gt;
        ///&lt;p&gt;If you did not make a request to update your account, please contact Administration - Support@MyDomain.Com&lt;/p&gt;
        ///&lt;p&gt;Thanking you,&lt;br/&gt;O&apos;Neill Says!&lt;/p&gt;.
        /// </summary>
        internal static string UserDetailsUpdatedTemplate {
            get {
                return ResourceManager.GetString("UserDetailsUpdatedTemplate", resourceCulture);
            }
        }
    }
}
