//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareMemories.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareMemories.Application.Resources.ApplicationText", typeof(ApplicationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}
        ///
        ///     Thank you for registering. Please confirm your email by clicking the link below:
        ///     
        ///     Confirm email link: {1}
        ///
        ///     If you did not register for this site, please ignore this email.
        ///
        ///     Thanking you
        ///     O&apos;Neill Says!.
        /// </summary>
        internal static string ConfirmEmailTemplate {
            get {
                return ResourceManager.GetString("ConfirmEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}
        ///
        /// We received a request to reset your password. Click the link below to reset it:
        /// 
        /// Reset password link: {1}
        ///
        /// If you did not request a password reset, please ignore this email.
        ///
        /// Thanking you
        /// O&apos;Neill Says!.
        /// </summary>
        internal static string ResetPasswordTemplate {
            get {
                return ResourceManager.GetString("ResetPasswordTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}
        ///
        ///You have received this 2FA email, as somebody is trying to log into your account. 
        ///If this is you, click on the link below to complete the login process:
        ///
        ///2FA link: {1}
        ///
        ///If you are not trying to log into your account, ignore this email and contact our administration team at the email address below.
        ///
        ///Administration Email: Support@MyDomain.Com
        ///
        ///Thanking you
        ///O&apos;Neill Says!.
        /// </summary>
        internal static string TwoFactorAuthenticationTemplate {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationTemplate", resourceCulture);
            }
        }
    }
}
