// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareMemories.Domain.Entities;

public partial class Friendship
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int FriendsWithId { get; set; }

    public bool? IsArchived { get; set; }


}