// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareMemories.Domain.Entities;

public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime? LastUpdated { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsArchived { get; set; }

    public virtual ICollection<Friendship> FriendshipFriendsWiths { get; set; } = new List<Friendship>();

    public virtual ICollection<Friendship> FriendshipUsers { get; set; } = new List<Friendship>();

    public virtual ICollection<Picture> Pictures { get; set; } = new List<Picture>();

    public virtual ICollection<Video> Videos { get; set; } = new List<Video>();
}